CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  author VARCHAR(255) NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title TEXT NOT NULL,
  text TEXT NOT NULL,
  likes INT DEFAULT 0,
  dislikes INT DEFAULT 0
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public reviews are viewable by everyone." ON public.reviews
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own reviews." ON public.reviews
  FOR INSERT WITH CHECK (true);
